apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: default
  labels:
    app: logstash
type: Opaque
stringData:
  # UPDATE THESE VALUES with your Elasticsearch credentials
  ELASTICSEARCH_HOST: "https://elasticsearch.example.com:9200"
  ELASTICSEARCH_USERNAME: "elastic"
  ELASTICSEARCH_PASSWORD: "changeme"
