apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-pq-pvc
  namespace: default
  labels:
    app: logstash
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # Storage for persistent queue (should be >= queue.max_bytes in logstash.yml)
      storage: 5Gi
  # Uncomment and set your storage class if needed
  # storageClassName: standard
